# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_HOST: mysql
          MYSQL_DATABASE: circle_test
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_PORT: 3306
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3
      - image: mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_HOST: mysql
          MYSQL_DATABASE: circle_test
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_PORT: 3306
    steps:
      - checkout
      # run tests!
      - run: npm test

  workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - test:
          requires:
            - build
